language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - tip

before_install:
  - "echo 'exec before_install'"
install:
  - "echo 'exec install'"
before_script:
  - "echo 'exec before_script'"
# script:
#   - "echo 'exec script'"
after_success:
  - "echo 'exec after_success'"
after_failure:
  - "echo 'exec after_failure'"
after_script:
  - "echo 'exec after_script'"

